from fastapi import status

class HTTPStatus:
    OK = status.HTTP_200_OK
    BAD_REQUEST = status.HTTP_400_BAD_REQUEST
    INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
    UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
    FORBIDDEN = status.HTTP_403_FORBIDDEN
    NOT_FOUND = status.HTTP_404_NOT_FOUND
